### PR TITLE
[WIP] add support for MOI Hermitian PSD cone

### LINKED ISSUE #821: Add support for MOI.HermitianPositiveSemidefiniteConeTriangle
If I create a model in JuMP with `model = Model(Hypatia.Optimizer; add_bridges=false)`, add a Hermitian PSD variable `@variable(model, [1:2, 1:2] in HermitianPSDCone())`, and try to optimize it I get the error 

"MathOptInterface.UnsupportedConstraint{MathOptInterface.VectorOfVariables, MathOptInterface.HermitianPositiveSemidefiniteConeTriangle}: `MathOptInterface.VectorOfVariables`-in-`MathOptInterface.HermitianPositiveSemidefiniteConeTriangle` constraint is not supported by the model"

But Hypatia supposedly does support it, see [the documentation](https://chriscoey.github.io/Hypatia.jl/dev/api/cones/#Hypatia.Cones.PosSemidefTri).

If I add instead `@variable(model, [1:2, 1:2] in PSDCone())` it works as expected.

I opened this issue before in JuMP jump-dev/JuMP.jl#3306, but the dev @odow told me that it needs to be supported here, not there.

### PR DESCRIPTION
**Pull request by chriscoey**
well this was a bit of a pain because MOI chose a different definition of the Hermitian PSD cone to what we had implemented

fixes #821

### CODE REVIEW

**Comment by chriscoey** [comment]
tested via a new complex polynomial minimization JuMP example, and a couple of MOI.Test Hermitian PSD cone tests, but I feel that more such tests need to be added to MOI.Test. this isn't as easy as it used to be because these tests have to have known analytical solutions. 

anyway, there's a chance a bug slipped in here, @araujoms, so please be vigilant as you try out using the JuMP HermitianPSDCone with Hypatia (after I merge and tag a new version).

**Comment by araujoms** [comment]
You can use my code [here](https://jump.dev/JuMP.jl/stable/tutorials/conic/quantum_discrimination/) for testing, it has the analytical answer for comparison.

**Comment by chriscoey** [comment]
Nice code. Would you mind running it against this branch to check that it works as expected? (I just spent 8 hours on this and am behind on my real job 😅)

**Comment by araujoms** [comment]
Ok, I've tested it here, works like a charm.

I'm just unhappy that Hypatia doesn't say the number of variables and constraints it is using, so I can't know whether it is using complex numbers optimally short of benchmarking.

**Comment by araujoms** [comment]
I did get an unrelated error when adding your branch 
```
    Updating ┌ Error: Error watching manifest
│   exception =
│    invalid redefinition of type Solver
```

**Comment by chriscoey** [comment]
> Ok, I've tested it here, works like a charm.
> 
> I'm just unhappy that Hypatia doesn't say the number of variables and constraints it is using, so I can't know whether it is using complex numbers optimally short of benchmarking.

you can get that info by dev'ing hypatia and adding some print functions internally, for example.


> I did get an unrelated error when adding your branch
> 
>     Updating ┌ Error: Error watching manifest
> │   exception =
> │    invalid redefinition of type Solver

i think you must have done something a little strange to see that. shouldn't happen in a fresh julia session


> Since I'm already annoying you, I hope you don't mind if I ask an unrelated question. I've added a new domain to do polynomial optimization. When I add it to the Hypatia file realdomains.jl I works, but if I paste the same code in my own file I get an error. Any idea what the problem might be? I really don't want to be messing with the package files.

maybe you need to import certain definitions from Hypatia before extending them. that said, it's not a huge deal to mess with certain package files for running experiments. everything is pretty modular and abstracted, so making changes to realdomains.jl shouldn't really cause anything scary to happen

**Comment by araujoms** [comment]
> you can get that info by dev'ing hypatia and adding some print functions internally, for example.

Indeed I can. I would suggest making Hypatia always print this information (if verbose), as all other solvers do.

> i think you must have done something a little strange to see that. shouldn't happen in a fresh julia session

Indeed, it didn't show up again.

> maybe you need to import certain definitions from Hypatia before extending them. that said, it's not a huge deal to mess with certain package files for running experiments. everything is pretty modular and abstracted, so making changes to realdomains.jl shouldn't really cause anything scary to happen

Thanks a lot, that was it. I did make sure to import `Domain`, but I hadn't noticed that I also needed to import `dimension`, `sample`, `degree`, and `weights`. I wasn't afraid of breaking anything, I just didn't want to maintain a local fork of Hypatia just for that.

**Comment by chriscoey** [comment]
@odow there's a failing test_model_ScalarFunctionConstantNotZero with BigFloat:
```
test_model_ScalarFunctionConstantNotZero: Test Failed at /home/runner/.julia/packages/MathOptInterface/wx5Ea/src/Test/test_model.jl:761
  Expression: err == _error(MOI.EqualTo{T}, T(1))
   Evaluated: MathOptInterface.ScalarFunctionConstantNotZero{BigFloat, MathOptInterface.ScalarAffineFunction{BigFloat}, MathOptInterface.EqualTo{BigFloat}}(1.0) == MathOptInterface.ScalarFunctionConstantNotZero{BigFloat, MathOptInterface.ScalarAffineFunction{BigFloat}, MathOptInterface.EqualTo{BigFloat}}(1.0)
Stacktrace:
 [1] macro expansion
   @ /opt/hostedtoolcache/julia/1.8.5/x64/share/julia/stdlib/v1.8/Test/src/Test.jl:464 [inlined]
 [2] test_model_ScalarFunctionConstantNotZero(model::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Hypatia.Optimizer{BigFloat}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{BigFloat}}}}, config::MathOptInterface.Test.Config{BigFloat})
   @ MathOptInterface.Test ~/.julia/packages/MathOptInterface/wx5Ea/src/Test/test_model.jl:761
test_model_ScalarFunctionConstantNotZero: Test Failed at /home/runner/.julia/packages/MathOptInterface/wx5Ea/src/Test/test_model.jl:770
  Expression: err == _error(MOI.GreaterThan{T}, T(2))
   Evaluated: MathOptInterface.ScalarFunctionConstantNotZero{BigFloat, MathOptInterface.ScalarAffineFunction{BigFloat}, MathOptInterface.GreaterThan{BigFloat}}(2.0) == MathOptInterface.ScalarFunctionConstantNotZero{BigFloat, MathOptInterface.ScalarAffineFunction{BigFloat}, MathOptInterface.GreaterThan{BigFloat}}(2.0)
Stacktrace:
 [1] macro expansion
   @ /opt/hostedtoolcache/julia/1.8.5/x64/share/julia/stdlib/v1.8/Test/src/Test.jl:464 [inlined]
 [2] test_model_ScalarFunctionConstantNotZero(model::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Hypatia.Optimizer{BigFloat}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{BigFloat}}}}, config::MathOptInterface.Test.Config{BigFloat})
   @ MathOptInterface.Test ~/.julia/packages/MathOptInterface/wx5Ea/src/Test/test_model.jl:770
```
I'm going to run fewer MOI bigfloat tests again, because they're too slow, so this won't be run in the next commit. but I'm still not sure why it's failing - any ideas?

**Comment by odow** [comment]
> i think you must have done something a little strange to see that. shouldn't happen in a fresh Julia session

This happens when you are using Revise.jl. It can't update when structs are changed. Reload the Julia session.

> test_model_ScalarFunctionConstantNotZero

Hmm. It can't compare because of the `BigFloat`? Not sure. Just skip it. The test is optional.

**Comment by chriscoey** [comment]
@araujoms i just tagged a new minor version, it should be available later today

**Pull request merged**
