### PR TITLE
MOI to 0.10

### PR DESCRIPTION
**Pull request by matbesancon**
Bump MOI to 0.10.
I fixed the obvious issues, the tests might still be a pain

Edit: since Hypatia does not use MOI.Test, this should be fine

### CODE REVIEW

**Comment by chriscoey** [comment]
thanks @matbesancon! for some reason I don't get email notifications so I didn't see this, but go ahead and merge if it's finished!

**Comment by matbesancon** [comment]
Thanks! This PR replaces #753, I don't think maintaining the two versions of MOI at the same time is feasible
I spoke too quickly about MOI tests, there are some of them, I'll fix them

**Comment by matbesancon** [comment]
I'm currently doing it on the SCIP wrapper, should have grasped it enough to transfer it to Hypatia soon

**Comment by matbesancon** [comment]
OK this seems to be working, it might be worth it to check more MOI tests but most of those that were in the old tests are running now

**Comment by matbesancon** [comment]
The error happening is in JuMP, I guess this is linked to JuMP not being updated to MOI 0.10?

**Comment by matbesancon** [comment]
also the next blocker will be up-ing PolyJuMP to MOI 0.10

**Comment by matbesancon** [comment]
Still blocked by https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/101 which blocks depenencies up to PolyJuMP

**Comment by matbesancon** [comment]
should be good now :crossed_fingers:

**Comment by matbesancon** [comment]
talked too quickly, still blocked by SOS

**Comment by chriscoey** [comment]
I reran but it failed again. JuMP is failing to precompile:
```
ERROR: LoadError: LoadError: UndefVarError: Grisu not defined
...
in expression starting at /home/runner/.julia/packages/JuMP/I7whV/src/writers.jl:5
in expression starting at /home/runner/.julia/packages/JuMP/I7whV/src/JuMP.jl:11
all tests: Error During Test at /home/runner/work/Hypatia.jl/Hypatia.jl/test/runtests.jl:25
  Got exception outside of a @test
  LoadError: LoadError: LoadError: Failed to precompile JuMP [4076af6c-e467-56ae-b986-b466b2749572] to /home/runner/.julia/compiled/v1.6/JuMP/jl_sYsTfo.
```

**Comment by chriscoey** [comment]
my guess is it's installing an old version of JuMP? because src/writers.jl doesn't exist anymore in JuMP

**Comment by chriscoey** [comment]
OK yeah we need PolyJuMP and SumOfSquares to both work with JuMP 0.22 and be tagged. @blegat looks like SumOfSquares JuMP compat is not at 0.22 yet

**Comment by matbesancon** [comment]
PolyJuMP is waiting for a new release but master works now

**Comment by matbesancon** [comment]
and yes SumOfSquare will need to also get this release from PolyJuMP

**Comment by chriscoey** [comment]
runtests is now passing because I split the examples testing out, so the runtests deps don't include the lagging sumofsquares etc. but examples tests are still failing because of those deps

**Comment by chriscoey** [comment]
I'm going to merge despite examples failing because it's unclear how long we'll have to wait for the dependencies

**Pull request merged**
