### PR TITLE
reorder rescaling and permuting for h

### PR DESCRIPTION
**Pull request by lkapelevich**
Addresses #823, I think. 
The test should really come from MOI.Test.

### CODE REVIEW

**Comment by chriscoey** [comment]
Thank you @lkapelevich! @araujoms can you confirm this fixes the issue? @odow is it worth adding a small test like that in https://github.com/chriscoey/Hypatia.jl/issues/823#issuecomment-1552154862 to MOI.Test?

**Comment by araujoms** [comment]
It only fixes it for d=2, for larger d I still get primal infeasible.

**Comment by lkapelevich** [comment]
Indeed, still buggy. Oops. Trying again...

**Comment by lkapelevich** [comment]
The issue is reusing [this permutation ](https://github.com/chriscoey/Hypatia.jl/blob/master/src/MathOptInterface/transform.jl#L172) for both values and row indices, but they should be inverses of each other.

I think we have the opposite problem with the Nuclear/Spectral norm cones
```
m = JuMP.Model(()->Hypatia.Optimizer(rescale=false));
JuMP.@variable(m, X[1:6])
JuMP.@variable(m, t)
JuMP.@constraint(m, [t, vec(X)...] in MOI.NormSpectralCone(2, 3))
JuMP.@constraint(m, X .== collect(1:6))
JuMP.@objective(m, Min, t)
JuMP.optimize!(m);
@assert JuMP.value.(X) ≈ collect(1:6)
@assert JuMP.value.(t) ≈ opnorm(reshape(1:6, 2, 3)) # OK


m = JuMP.Model(()->Hypatia.Optimizer(rescale=false));
JuMP.@variable(m, X[1:6])
JuMP.@variable(m, t)
JuMP.@constraint(m, [t, vec(X)...] in MOI.NormSpectralCone(3, 2))
JuMP.@constraint(m, X .== collect(1:6))
JuMP.@objective(m, Min, t)
JuMP.optimize!(m);
@assert JuMP.value.(X) ≈ collect(1:6)
@assert JuMP.value.(t) ≈ opnorm(reshape(1:6, 3, 2)) # not OK
```

**Comment by odow** [comment]
I'll add some more tests to MOI

**Comment by lkapelevich** [comment]
Passing MOI tests, examples tests, my [gist tests](https://gist.github.com/lkapelevich/6ed090af6170f92cf8b4d70b975da296) (ideally all last 5 combinations of sets/functions would be in MOI.Test), and the original example from #822. Let me sanity-check one more time...

**Comment by odow** [comment]
Does `MOI.NormNuclearCone` have the same issue?

**Comment by lkapelevich** [comment]
> Does `MOI.NormNuclearCone` have the same issue?

Yes, it's the same code path

**Comment by odow** [comment]
Okay. I'll add tests for `NormNuclearCone` as well based on your gist

**Comment by chriscoey** [comment]
I'm sure this was tedious - thanks for being thorough. And thanks @odow for adding new MOI tests. I'll merge when green and make a new release.

**Comment by araujoms** [comment]
I can confirm, now it works for all dimensions. Thanks a lot.

**Pull request merged**
